apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mon-aws
  namespace: mediaflow
  labels:
    tier: admin
spec:
  storageClassName: standard
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
