apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongo-aws
  namespace: mediaflow
  labels:
    type: st1
    tier: backend
spec:
  storageClassName: gp2
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
