apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongo-aws
  namespace: mediaflow
  labels:
    type: cloud
    tier: backend
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data"
