apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: kubectl run node-app --image=legacywhisperer/node-app:latest --dry-run=true --replicas=3 --restart=Always --record=true --output=yaml
  creationTimestamp: null
  labels:
    run: node-react-app
  name: node-react-app
spec:
  replicas: 3
  selector:
    matchLabels:
      run: node-react-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: node-react-app
    spec:
      containers:
      - image: legacywhisperer/node-app:latest
        name: node-app
        env: 
        - name: MONGODB_URI
          value: mongodb:27017
      - image: legacywhisperer/react-app:latest
        name: react-app
        env: 
        - name: API_ROOT
          value:  'https://conduit.productionready.io/api'
---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: node-svc
  name: node-svc
spec:
  ports:
  - port: 3000
    nodePort: 30000
    protocol: TCP
    targetPort: 3000
  selector:
    run: node-svc
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: react-svc
  name: react-svc
spec:
  ports:
  - port: 4100
    protocol: TCP
    targetPort: 4100
    nodePort: 30001
  selector:
    run: react-svc
  type: NodePort
