apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mongo
  labels:
    type: local
    tier: backend
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data"
