apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: node-react-app
  name: react-svc
spec:
  ports:
  - port: 4100
    protocol: TCP
    targetPort: 4100
  selector:
    run: node-react-app
  type: ClusterIP
status:
  loadBalancer: {}
