apiVersion: v1
kind: PersistentVolume
metadata:
  name: aws-pv-mongo
  namespace: mediaflow
  labels:
    type: gp2
    tier: backend
spec:
  storageClassName: gp2
  capacity:
    storage: 20Gi
  accessModes:
  - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: 
    fsType: xfs

#  hostPath:
#    path: "/tmp/data"
