apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aws-pvc-mongo
  namespace: mediaflow
  labels: 
    tier: backend
spec:
  storageClassName: backend-storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
