apiVersion: v1
kind: PersistentVolume
metadata:
  name: aws-pv-mongo
  namespace: mediaflow
  labels:
    tier: backend
    type: backend-storage-class
spec:
  storageClassName: backend-storage-class
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
# dynamic allocation via sc above
  awsElasticBlockStore:
    fsType: ext4
    volumeID: vol-0e4f07f1975be574a
#
#  hostPath:
#    path: "/tmp/data"
# 
# USED PRIOR TO Dynamic Provisioning
