apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: mediaflow
spec: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mongodb
    tier: backend
  name: mongodb
  namespace: mediaflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      tier: backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mongodb
        tier: backend
    spec:
      containers:
      - image: mongo
        name: mongodb
        ports: 
          - containerPort: 27017
        env: 
        - name: MONGODB_URI
          value: mongodb://mongosvc:27017
        - name: API_ROOT
          value: http://node-svc:30000/api
        volumeMounts:
        - mountPath: "/data"
          name: aws-pv-mongo
      volumes:
      - name: aws-pv-mongo
        persistentVolumeClaim:
          claimName: aws-pvc-mongo
      
---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mongosvc
    tier: backend
  name: mongosvc
  namespace: mediaflow
spec:
  type: ClusterIP
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongosvc
    tier: backend

