apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/change-cause: kubectl run node-app --image=legacywhisperer/node-app:latest --dry-run=true --replicas=3 --restart=Always --record=true --output=yaml
  creationTimestamp: null
  labels:
    run: node-prod
    tier: api
  name: node
  namespace: mediaflow
spec:
  replicas: 3
  selector:
    matchLabels:
      run: node-prod
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: node-prod
        tier: api
    spec:
      containers:
      - image: legacywhisperer/node-app
        name: node-prod
        env:
        - name: API_ROOT
          value:  'http://nodesvc:30000/api'
        - name: SECRET
          value:  secret
        - name: NODE_ENV
          value:  'production'
        - name: APIURL
          value:  'http://nodesvc:30000/api'
#        - name: MONGODB_URI
#          value: 'mongodb+srv://conduitadmin:<password>@cpi.myzls.mongodb.net/<dbname>?retryWrites=true&w=majority
#
        - name: MONGODB_URI
          value: 'mongodb+srv://conduitadmin:<password>@mongosvc.mediaflow:30017/conduit'
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
             name: nodesecret
             key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nodesecret
              key: password
        ports: 
          - containerPort: 3000
        volumeMounts:
        - name: nodesecret
          mountPath: "/etc/nodesecret"
          readOnly: true
      volumes:
      - name: nodesecret
        secret:
          secretName: nodesecret
          defaultMode: 0400
           
---

apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: nodesvc
    tier: api
  name: nodesvc
  namespace: mediaflow
spec:
  ports:
  - nodePort: 30000
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    run: nodesvc
    tier: api
  type: NodePort
  
#  ports:
#    port: 4100
#    protocol: TCP
#    targetPort: 4100
#  selector:
#    run: reactsvc
#    tier: frontend
