---
apiVersion: mongodb.com/v1
kind: MongoDB
metadata:
  name: mongodb-standalone
spec:
  version: 4.2.2-ent
  opsManager:
    configMapRef:
      name: configMap.metadata.name
            # Must match metadata.name in ConfigMap file
  credentials: mycredentials
  type: Standalone
  persistent: true
