apiVersion: v1
kind: PersistentVolume
metadata:
  name: dev-pv-mongo
  namespace: mediaflow
  labels:
    tier: backend
    type: backend-storage-class
spec:
  storageClassName: backend-storage-class
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/data"
