apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"creationTimestamp":null,"labels":{"app":"mongosvc","tier":"backend"},"name":"mongosvc","namespace":"mediaflow"},"spec":{"ports":[{"nodePort":30017,"port":27017,"protocol":"TCP","targetPort":27017}],"selector":{"app":"mongosvc","tier":"backend"},"type":"NodePort"}}
  creationTimestamp: 2020-07-23T21:08:17Z
  labels:
    app: mongosvc
    tier: backend
  name: mongosvc
  namespace: mediaflow
  resourceVersion: "10136"
  selfLink: /api/v1/namespaces/mediaflow/services/mongosvc
  uid: 945ed449-cea2-461f-836a-932de4f5544f
spec:
  clusterIP: 10.100.170.148
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30017
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: mongosvc
    tier: backend
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
