apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dev-pvc-mongo
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-storage
